In [1]:
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import pandas as pd
import itertools
from itertools import islice
from DataAugmentationForObjectDetection.data_aug.data_aug import * #Script in the folder
from DataAugmentationForObjectDetection.data_aug.bbox_util import *

In [2]:
current_path = os.getcwd()

In [3]:
def full_augmentation(path,dirlist):
    path = os.path.join(os.getcwd(),"Data")
    directories = [dirnames for root,dirnames,filenames in os.walk(path)][0]

    train_img,valid_img,test_img = image_distribution(path,directories) #Storing images
    print("Loaded Image data")
    train_ano,valid_ano,test_ano = ano_distribution(path,directories) #Storing annotations
    print("Loaded annotation data")

    import itertools
    list2 = train_ano.copy()
    labels = {'Back_Rest':1,'Seat':2,'Left_armrest':3,'Right_armrest':4,'Base':5}
    for obj in itertools.chain.from_iterable(list2):
        obj[4] = labels[obj[4]]

    #ar = np.array(list2,dtype='float64')

    for index,image in enumerate(train_img):
        img = cv2.imread(image)[:,:,::-1] #opencv loads images in bgr. This converts it into rgb
        #test_anno = train_ano[0]
        ar = np.array(list2[index],dtype='float64')
        img_,bboxes_ = RandomHorizontalFlip(1)(img.copy(),ar.copy())
        plotted_img = draw_rect(img_,bboxes_)


In [4]:
#Split the images from train,valid and test folders into lists 
def image_distribution(path,dirlist):
    train,valid,test = [],[],[]
    for dir in dirlist:
        for img in os.listdir(os.path.join(path,dir)):
            if img.endswith(".jpg"):# Get only the images
                test.append(os.path.join(path,dir,img)) if dir == 'test' else (train.append(os.path.join(path,dir,img)) if dir == 'train' else valid.append(os.path.join(path,dir,img)))
    return train,valid,test

In [5]:
#Return a list which is having bounding box annotion format as required by data_aug.py methods  [x1,y1,x2,y2,class] for training test and validdation images 
def ano_bbox(path,dirlist):
    import xml.etree.cElementTree as et
    train,valid,test = [],[],[]
    for dir in dirlist:
        for annotation in os.listdir(os.path.join(path,dir)):
            if annotation.endswith(".xml"): # Get the xml files only 
                tree = et.parse(os.path.join(path,dir,annotation))
                root = tree.getroot()
                anno = []
                for tag in root.findall('object'):#iterates through all the labled objects in the image
                    order = [0,2,1,3] 
                    temp = [subtag.text for subtag in tag[5]] # Store coordinates of bounding box in a list
                    temp = [temp[i] for i in order] # Reordering the list to be x1,y1,x2,y2 instead of x1,x2,y1,y2
                    temp.append(tag[0].text) #Get the class  
                    anno.append(temp)
                test.append(anno) if dir == 'test' else (train.append(anno) if dir == 'train' else valid.append(anno))
    return train,valid,test

In [101]:
def ano_polygon(path,dirlist):
    import xml.etree.cElementTree as et
    train,valid,test = [],[],[]
    for dir in dirlist:
        for annotation in os.listdir(os.path.join(path,dir)):
            if annotation.endswith(".xml"): # Get the xml files only 
                tree = et.parse(os.path.join(path,dir,annotation))
                root = tree.getroot()
                anno = []
                for tag in root.findall('object'):#iterates through all the labled objects in the image
                    #order = [0,2,1,3] 
                    temp = [subtag.text for subtag in tag[6]] # Store coordinates of bounding box in a list
                    print("start")
                    #temp = list(iter(lambda:list(islice(temp,2)),()))
                    print("end")
                    temp.append(tag[0].text) #Get the class  
                    anno.append(temp)
                test.append(anno) if dir == 'test' else (train.append(anno) if dir == 'train' else valid.append(anno))
    return train,valid,test

In [ ]:
def create_annotation_xml(bbox):


In [97]:
import xml.etree.cElementTree as et
path = os.path.join(os.getcwd(),"Data")
directories = [dirnames for root,dirnames,filenames in os.walk(path)][0]
for dir in directories:
    for annotation in os.listdir(os.path.join(path,dir)):
        if annotation.endswith(".xml"): # Get the xml files only 
            tree = et.parse(os.path.join(path,dir,annotation))
            root = tree.getroot()
            anno = []
            for tag in root.findall('object'):#iterates through all the labled objects in the image
                #order = [0,2,1,3] 
                try:
                    temp = [subtag.text for subtag in tag[6]]
                except:
                    print("Polygon not found",annotation,dir)

In [92]:
tree = et.parse(r'D:\Assignment\Image_Augmentation\Data\train\20230119_115302_jpg.rf.1b7319ba4033ff7eb54fb305f2c0c195.xml')
root = tree.getroot()
try:
    print(root.findall('object')[0][6])    
    print(root.findall('object')[0][6][0].text)
except:
    print("No")


<Element 'polygon' at 0x000002556BD32110>
193.771626


In [102]:
path = os.path.join(os.getcwd(),"Data")
directories = [dirnames for root,dirnames,filenames in os.walk(path)][0]
train_poly,valid_poly,test_poly = ano_polygon(path,directories) #Storing annotations
print("Loaded annotation data")

start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end
start
end


In [54]:
if __name__ == '__main__':
    path = os.path.join(os.getcwd(),"Data")
    directories = [dirnames for root,dirnames,filenames in os.walk(path)][0]

    train_img,valid_img,test_img = image_distribution(path,directories) #Storing images
    print("Loaded Image data")
    train_ano,valid_ano,test_ano = ano_bbox(path,directories) #Storing annotations
    print("Loaded bounding box data")
    train_poly,valid_poly,test_poly = ano_polygon(path,directories) #Storing annotations
    print("Loaded annotation data")

    
    list2 = train_ano.copy()
    labels = {'Back_Rest':1,'Seat':2,'Left_armrest':3,'Right_armrest':4,'Base':5}
    for obj in itertools.chain.from_iterable(list2):
        obj[4] = labels[obj[4]]

    #ar = np.array(list2,dtype='float64')
    plotted_img_list = []
    bbox_list = []
    suffix = 0
    for index,image in enumerate(train_img):
        img = cv2.imread(image)[:,:,::-1] #opencv loads images in bgr. This converts it into rgb
        #test_anno = train_ano[0]
        ar = np.array(list2[index],dtype='float64')
        #img_,bboxes_ = RandomHorizontalFlip(1)(img.copy(),ar.copy())
        seq = Sequence([RandomHSV(40, 40, 30),RandomHorizontalFlip(), RandomScale(), RandomTranslate(), RandomRotate(10), RandomShear()])
        img_, bboxes_ = seq(img.copy(), ar.copy())
        plotted_img = draw_rect(img_,bboxes_)
        os.chdir("D:\Assignment\Augmentation")
        cv2.imwrite(filename="C"+str(suffix)+".jpg",img=plotted_img)
        suffix += 1
        seq = Sequence([RandomScale(), RandomRotate(30), RandomShear()])
        img_, bboxes_ = seq(img.copy(), ar.copy())
        plotted_img = draw_rect(img_,bboxes_)
        cv2.imwrite(filename="C"+str(suffix)+".jpg",img=plotted_img)
        suffix += 1
        os.chdir(current_path)
        #plotted_img_list.append(img_)
        #bbox_list.append(bboxes_)
        #plt.imshow(plotted_img)
        #plt.show()

Loaded Image data
Loaded bounding box data


KeyboardInterrupt: 

In [30]:
a = ar[:,:-1]
a


array([[ 11., 137., 568., 343.],
       [177., 323., 463., 549.],
       [ 51., 358., 145., 495.],
       [474., 357., 562., 497.]])

In [37]:
for pt in a.reshape(-1,1,2):
    print(pt)

[[ 11. 137.]]
[[568. 343.]]
[[177. 323.]]
[[463. 549.]]
[[ 51. 358.]]
[[145. 495.]]
[[474. 357.]]
[[562. 497.]]


In [44]:
x = np.arange(30,400,20)
y = np.sqrt(x*2)
print(x,y)

[ 30  50  70  90 110 130 150 170 190 210 230 250 270 290 310 330 350 370
 390] [ 7.74596669 10.         11.83215957 13.41640786 14.83239697 16.1245155
 17.32050808 18.43908891 19.49358869 20.49390153 21.44761059 22.36067977
 23.23790008 24.08318916 24.8997992  25.69046516 26.45751311 27.20294102
 27.92848009]
